// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contribledger/contrib/v1/contribution.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Contribution defines the Contribution message.
type Contribution struct {
	Index               string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	UserId              string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WeightUpdate        uint64 `protobuf:"varint,3,opt,name=weight_update,json=weightUpdate,proto3" json:"weight_update,omitempty"`
	ConvergenceSpeed    uint64 `protobuf:"varint,4,opt,name=convergence_speed,json=convergenceSpeed,proto3" json:"convergence_speed,omitempty"`
	AccuracyImprovement uint64 `protobuf:"varint,5,opt,name=accuracy_improvement,json=accuracyImprovement,proto3" json:"accuracy_improvement,omitempty"`
	ContributionScore   uint64 `protobuf:"varint,6,opt,name=contribution_score,json=contributionScore,proto3" json:"contribution_score,omitempty"`
	Timestamp           int64  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Creator             string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Contribution) Reset()         { *m = Contribution{} }
func (m *Contribution) String() string { return proto.CompactTextString(m) }
func (*Contribution) ProtoMessage()    {}
func (*Contribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7fd86fe6ace0c66, []int{0}
}
func (m *Contribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contribution.Merge(m, src)
}
func (m *Contribution) XXX_Size() int {
	return m.Size()
}
func (m *Contribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Contribution.DiscardUnknown(m)
}

var xxx_messageInfo_Contribution proto.InternalMessageInfo

func (m *Contribution) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Contribution) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Contribution) GetWeightUpdate() uint64 {
	if m != nil {
		return m.WeightUpdate
	}
	return 0
}

func (m *Contribution) GetConvergenceSpeed() uint64 {
	if m != nil {
		return m.ConvergenceSpeed
	}
	return 0
}

func (m *Contribution) GetAccuracyImprovement() uint64 {
	if m != nil {
		return m.AccuracyImprovement
	}
	return 0
}

func (m *Contribution) GetContributionScore() uint64 {
	if m != nil {
		return m.ContributionScore
	}
	return 0
}

func (m *Contribution) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Contribution) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Contribution)(nil), "contribledger.contrib.v1.Contribution")
}

func init() {
	proto.RegisterFile("contribledger/contrib/v1/contribution.proto", fileDescriptor_c7fd86fe6ace0c66)
}

var fileDescriptor_c7fd86fe6ace0c66 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x3f, 0x4f, 0x02, 0x31,
	0x18, 0xc6, 0x29, 0x7f, 0xa5, 0xc1, 0x44, 0x2a, 0x89, 0x1d, 0xb4, 0x21, 0xba, 0x90, 0x10, 0x21,
	0xc4, 0xc1, 0x5d, 0x27, 0x56, 0x88, 0x8b, 0xcb, 0xe5, 0x68, 0xdf, 0x60, 0x13, 0xaf, 0x6d, 0x7a,
	0xbd, 0x13, 0xbe, 0x85, 0x5f, 0xc3, 0x6f, 0xe2, 0xc8, 0xe8, 0x68, 0xee, 0xbe, 0x88, 0xb9, 0xc2,
	0xc9, 0xb1, 0xf5, 0xf9, 0xfd, 0x9e, 0x0e, 0x6f, 0x1e, 0x3c, 0xe6, 0x5a, 0x39, 0x2b, 0x57, 0xef,
	0x20, 0xd6, 0x60, 0xa7, 0x87, 0x34, 0x4d, 0x67, 0xe5, 0x33, 0x71, 0x52, 0xab, 0x89, 0xb1, 0xda,
	0x69, 0x42, 0x4f, 0xca, 0x93, 0x43, 0x9a, 0xa4, 0xb3, 0xdb, 0xaf, 0x3a, 0xee, 0x3d, 0x57, 0x3e,
	0x90, 0x01, 0x6e, 0x49, 0x25, 0x60, 0x43, 0xd1, 0x10, 0x8d, 0xba, 0x8b, 0x7d, 0x20, 0x57, 0xb8,
	0x93, 0xc4, 0x60, 0x03, 0x29, 0x68, 0xdd, 0xf3, 0x76, 0x11, 0xe7, 0x82, 0xdc, 0xe1, 0xf3, 0x0f,
	0x90, 0xeb, 0x37, 0x17, 0x24, 0x46, 0x84, 0x0e, 0x68, 0x63, 0x88, 0x46, 0xcd, 0x45, 0x6f, 0x0f,
	0x5f, 0x3c, 0x23, 0x63, 0xdc, 0xe7, 0x5a, 0xa5, 0x60, 0xd7, 0xa0, 0x38, 0x04, 0xb1, 0x01, 0x10,
	0xb4, 0xe9, 0x8b, 0x17, 0x15, 0xb1, 0x2c, 0x38, 0x99, 0xe1, 0x41, 0xc8, 0x79, 0x62, 0x43, 0xbe,
	0x0d, 0x64, 0x64, 0xac, 0x4e, 0x21, 0x02, 0xe5, 0x68, 0xcb, 0xf7, 0x2f, 0x4b, 0x37, 0x3f, 0x2a,
	0x72, 0x8f, 0x49, 0xf5, 0xe8, 0x20, 0xe6, 0xda, 0x02, 0x6d, 0xfb, 0x0f, 0xfd, 0xaa, 0x59, 0x16,
	0x82, 0x5c, 0xe3, 0xae, 0x93, 0x11, 0xc4, 0x2e, 0x8c, 0x0c, 0xed, 0x0c, 0xd1, 0xa8, 0xb1, 0x38,
	0x02, 0x42, 0x71, 0x87, 0x5b, 0x08, 0x9d, 0xb6, 0xf4, 0xcc, 0x9f, 0x5a, 0xc6, 0xa7, 0xc7, 0xef,
	0x8c, 0xa1, 0x5d, 0xc6, 0xd0, 0x6f, 0xc6, 0xd0, 0x67, 0xce, 0x6a, 0xbb, 0x9c, 0xd5, 0x7e, 0x72,
	0x56, 0x7b, 0xbd, 0x39, 0x1d, 0x63, 0xf3, 0x3f, 0x87, 0xdb, 0x1a, 0x88, 0x57, 0x6d, 0xbf, 0xc2,
	0xc3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x94, 0x13, 0x31, 0xb4, 0x01, 0x00, 0x00,
}

func (m *Contribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x42
	}
	if m.Timestamp != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x38
	}
	if m.ContributionScore != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.ContributionScore))
		i--
		dAtA[i] = 0x30
	}
	if m.AccuracyImprovement != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.AccuracyImprovement))
		i--
		dAtA[i] = 0x28
	}
	if m.ConvergenceSpeed != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.ConvergenceSpeed))
		i--
		dAtA[i] = 0x20
	}
	if m.WeightUpdate != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.WeightUpdate))
		i--
		dAtA[i] = 0x18
	}
	if len(m.UserId) > 0 {
		i -= len(m.UserId)
		copy(dAtA[i:], m.UserId)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.UserId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintContribution(dAtA []byte, offset int, v uint64) int {
	offset -= sovContribution(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	if m.WeightUpdate != 0 {
		n += 1 + sovContribution(uint64(m.WeightUpdate))
	}
	if m.ConvergenceSpeed != 0 {
		n += 1 + sovContribution(uint64(m.ConvergenceSpeed))
	}
	if m.AccuracyImprovement != 0 {
		n += 1 + sovContribution(uint64(m.AccuracyImprovement))
	}
	if m.ContributionScore != 0 {
		n += 1 + sovContribution(uint64(m.ContributionScore))
	}
	if m.Timestamp != 0 {
		n += 1 + sovContribution(uint64(m.Timestamp))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	return n
}

func sovContribution(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContribution(x uint64) (n int) {
	return sovContribution(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContribution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightUpdate", wireType)
			}
			m.WeightUpdate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WeightUpdate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConvergenceSpeed", wireType)
			}
			m.ConvergenceSpeed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConvergenceSpeed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccuracyImprovement", wireType)
			}
			m.AccuracyImprovement = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccuracyImprovement |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionScore", wireType)
			}
			m.ContributionScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContributionScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContribution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContribution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContribution(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContribution
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContribution
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContribution
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContribution
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContribution        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContribution          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContribution = fmt.Errorf("proto: unexpected end of group")
)
