// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contribledger/contrib/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgSubmitContribution defines the MsgSubmitContribution message.
type MsgSubmitContribution struct {
	Creator             string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	UserId              string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WeightUpdate        uint64 `protobuf:"varint,3,opt,name=weight_update,json=weightUpdate,proto3" json:"weight_update,omitempty"`
	ConvergenceSpeed    uint64 `protobuf:"varint,4,opt,name=convergence_speed,json=convergenceSpeed,proto3" json:"convergence_speed,omitempty"`
	AccuracyImprovement uint64 `protobuf:"varint,5,opt,name=accuracy_improvement,json=accuracyImprovement,proto3" json:"accuracy_improvement,omitempty"`
	ContributionScore   uint64 `protobuf:"varint,6,opt,name=contribution_score,json=contributionScore,proto3" json:"contribution_score,omitempty"`
}

func (m *MsgSubmitContribution) Reset()         { *m = MsgSubmitContribution{} }
func (m *MsgSubmitContribution) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitContribution) ProtoMessage()    {}
func (*MsgSubmitContribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{2}
}
func (m *MsgSubmitContribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitContribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitContribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitContribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitContribution.Merge(m, src)
}
func (m *MsgSubmitContribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitContribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitContribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitContribution proto.InternalMessageInfo

func (m *MsgSubmitContribution) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitContribution) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MsgSubmitContribution) GetWeightUpdate() uint64 {
	if m != nil {
		return m.WeightUpdate
	}
	return 0
}

func (m *MsgSubmitContribution) GetConvergenceSpeed() uint64 {
	if m != nil {
		return m.ConvergenceSpeed
	}
	return 0
}

func (m *MsgSubmitContribution) GetAccuracyImprovement() uint64 {
	if m != nil {
		return m.AccuracyImprovement
	}
	return 0
}

func (m *MsgSubmitContribution) GetContributionScore() uint64 {
	if m != nil {
		return m.ContributionScore
	}
	return 0
}

// MsgSubmitContributionResponse defines the MsgSubmitContributionResponse message.
type MsgSubmitContributionResponse struct {
}

func (m *MsgSubmitContributionResponse) Reset()         { *m = MsgSubmitContributionResponse{} }
func (m *MsgSubmitContributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitContributionResponse) ProtoMessage()    {}
func (*MsgSubmitContributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{3}
}
func (m *MsgSubmitContributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitContributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitContributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitContributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitContributionResponse.Merge(m, src)
}
func (m *MsgSubmitContributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitContributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitContributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitContributionResponse proto.InternalMessageInfo

// MsgCreateContribution defines the MsgCreateContribution message.
type MsgCreateContribution struct {
	Creator             string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index               string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	UserId              string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WeightUpdate        uint64 `protobuf:"varint,4,opt,name=weight_update,json=weightUpdate,proto3" json:"weight_update,omitempty"`
	ConvergenceSpeed    uint64 `protobuf:"varint,5,opt,name=convergence_speed,json=convergenceSpeed,proto3" json:"convergence_speed,omitempty"`
	AccuracyImprovement uint64 `protobuf:"varint,6,opt,name=accuracy_improvement,json=accuracyImprovement,proto3" json:"accuracy_improvement,omitempty"`
	ContributionScore   uint64 `protobuf:"varint,7,opt,name=contribution_score,json=contributionScore,proto3" json:"contribution_score,omitempty"`
	Timestamp           int64  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *MsgCreateContribution) Reset()         { *m = MsgCreateContribution{} }
func (m *MsgCreateContribution) String() string { return proto.CompactTextString(m) }
func (*MsgCreateContribution) ProtoMessage()    {}
func (*MsgCreateContribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{4}
}
func (m *MsgCreateContribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateContribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateContribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateContribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateContribution.Merge(m, src)
}
func (m *MsgCreateContribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateContribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateContribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateContribution proto.InternalMessageInfo

func (m *MsgCreateContribution) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateContribution) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgCreateContribution) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MsgCreateContribution) GetWeightUpdate() uint64 {
	if m != nil {
		return m.WeightUpdate
	}
	return 0
}

func (m *MsgCreateContribution) GetConvergenceSpeed() uint64 {
	if m != nil {
		return m.ConvergenceSpeed
	}
	return 0
}

func (m *MsgCreateContribution) GetAccuracyImprovement() uint64 {
	if m != nil {
		return m.AccuracyImprovement
	}
	return 0
}

func (m *MsgCreateContribution) GetContributionScore() uint64 {
	if m != nil {
		return m.ContributionScore
	}
	return 0
}

func (m *MsgCreateContribution) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// MsgCreateContributionResponse defines the MsgCreateContributionResponse message.
type MsgCreateContributionResponse struct {
}

func (m *MsgCreateContributionResponse) Reset()         { *m = MsgCreateContributionResponse{} }
func (m *MsgCreateContributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateContributionResponse) ProtoMessage()    {}
func (*MsgCreateContributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{5}
}
func (m *MsgCreateContributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateContributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateContributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateContributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateContributionResponse.Merge(m, src)
}
func (m *MsgCreateContributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateContributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateContributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateContributionResponse proto.InternalMessageInfo

// MsgUpdateContribution defines the MsgUpdateContribution message.
type MsgUpdateContribution struct {
	Creator             string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index               string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	UserId              string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WeightUpdate        uint64 `protobuf:"varint,4,opt,name=weight_update,json=weightUpdate,proto3" json:"weight_update,omitempty"`
	ConvergenceSpeed    uint64 `protobuf:"varint,5,opt,name=convergence_speed,json=convergenceSpeed,proto3" json:"convergence_speed,omitempty"`
	AccuracyImprovement uint64 `protobuf:"varint,6,opt,name=accuracy_improvement,json=accuracyImprovement,proto3" json:"accuracy_improvement,omitempty"`
	ContributionScore   uint64 `protobuf:"varint,7,opt,name=contribution_score,json=contributionScore,proto3" json:"contribution_score,omitempty"`
	Timestamp           int64  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *MsgUpdateContribution) Reset()         { *m = MsgUpdateContribution{} }
func (m *MsgUpdateContribution) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateContribution) ProtoMessage()    {}
func (*MsgUpdateContribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{6}
}
func (m *MsgUpdateContribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateContribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateContribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateContribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateContribution.Merge(m, src)
}
func (m *MsgUpdateContribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateContribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateContribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateContribution proto.InternalMessageInfo

func (m *MsgUpdateContribution) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateContribution) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgUpdateContribution) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MsgUpdateContribution) GetWeightUpdate() uint64 {
	if m != nil {
		return m.WeightUpdate
	}
	return 0
}

func (m *MsgUpdateContribution) GetConvergenceSpeed() uint64 {
	if m != nil {
		return m.ConvergenceSpeed
	}
	return 0
}

func (m *MsgUpdateContribution) GetAccuracyImprovement() uint64 {
	if m != nil {
		return m.AccuracyImprovement
	}
	return 0
}

func (m *MsgUpdateContribution) GetContributionScore() uint64 {
	if m != nil {
		return m.ContributionScore
	}
	return 0
}

func (m *MsgUpdateContribution) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// MsgUpdateContributionResponse defines the MsgUpdateContributionResponse message.
type MsgUpdateContributionResponse struct {
}

func (m *MsgUpdateContributionResponse) Reset()         { *m = MsgUpdateContributionResponse{} }
func (m *MsgUpdateContributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateContributionResponse) ProtoMessage()    {}
func (*MsgUpdateContributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{7}
}
func (m *MsgUpdateContributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateContributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateContributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateContributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateContributionResponse.Merge(m, src)
}
func (m *MsgUpdateContributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateContributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateContributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateContributionResponse proto.InternalMessageInfo

// MsgDeleteContribution defines the MsgDeleteContribution message.
type MsgDeleteContribution struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index   string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *MsgDeleteContribution) Reset()         { *m = MsgDeleteContribution{} }
func (m *MsgDeleteContribution) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteContribution) ProtoMessage()    {}
func (*MsgDeleteContribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{8}
}
func (m *MsgDeleteContribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteContribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteContribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteContribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteContribution.Merge(m, src)
}
func (m *MsgDeleteContribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteContribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteContribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteContribution proto.InternalMessageInfo

func (m *MsgDeleteContribution) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteContribution) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

// MsgDeleteContributionResponse defines the MsgDeleteContributionResponse message.
type MsgDeleteContributionResponse struct {
}

func (m *MsgDeleteContributionResponse) Reset()         { *m = MsgDeleteContributionResponse{} }
func (m *MsgDeleteContributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteContributionResponse) ProtoMessage()    {}
func (*MsgDeleteContributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb667ea81b58a31d, []int{9}
}
func (m *MsgDeleteContributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteContributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteContributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteContributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteContributionResponse.Merge(m, src)
}
func (m *MsgDeleteContributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteContributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteContributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteContributionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "contribledger.contrib.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "contribledger.contrib.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgSubmitContribution)(nil), "contribledger.contrib.v1.MsgSubmitContribution")
	proto.RegisterType((*MsgSubmitContributionResponse)(nil), "contribledger.contrib.v1.MsgSubmitContributionResponse")
	proto.RegisterType((*MsgCreateContribution)(nil), "contribledger.contrib.v1.MsgCreateContribution")
	proto.RegisterType((*MsgCreateContributionResponse)(nil), "contribledger.contrib.v1.MsgCreateContributionResponse")
	proto.RegisterType((*MsgUpdateContribution)(nil), "contribledger.contrib.v1.MsgUpdateContribution")
	proto.RegisterType((*MsgUpdateContributionResponse)(nil), "contribledger.contrib.v1.MsgUpdateContributionResponse")
	proto.RegisterType((*MsgDeleteContribution)(nil), "contribledger.contrib.v1.MsgDeleteContribution")
	proto.RegisterType((*MsgDeleteContributionResponse)(nil), "contribledger.contrib.v1.MsgDeleteContributionResponse")
}

func init() { proto.RegisterFile("contribledger/contrib/v1/tx.proto", fileDescriptor_eb667ea81b58a31d) }

var fileDescriptor_eb667ea81b58a31d = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x96, 0x3d, 0x6f, 0xd3, 0x40,
	0x18, 0xc7, 0xe3, 0xe6, 0xa5, 0xe4, 0x28, 0x82, 0x1e, 0x41, 0x75, 0x23, 0xea, 0x86, 0x20, 0x44,
	0x28, 0x6a, 0xac, 0x14, 0x89, 0x4a, 0xdd, 0x68, 0x59, 0x3a, 0x44, 0x42, 0x8e, 0x58, 0x58, 0x2c,
	0xc7, 0x3e, 0xb9, 0x96, 0x62, 0x9f, 0x75, 0x77, 0x0e, 0xc9, 0x82, 0x10, 0x23, 0x13, 0x9f, 0x02,
	0x31, 0x66, 0xe0, 0x43, 0x54, 0x4c, 0x15, 0x13, 0x62, 0x40, 0x28, 0x19, 0xf2, 0x1d, 0x98, 0x90,
	0x7d, 0xce, 0xab, 0xed, 0xbc, 0x08, 0x75, 0x63, 0x89, 0xf2, 0xbc, 0xdd, 0xff, 0x79, 0x7e, 0x3a,
	0x3f, 0x36, 0x78, 0xa0, 0x63, 0x87, 0x11, 0xab, 0xd9, 0x42, 0x86, 0x89, 0x88, 0x1c, 0x5a, 0x72,
	0xbb, 0x26, 0xb3, 0x4e, 0xd5, 0x25, 0x98, 0x61, 0x28, 0xce, 0xa4, 0x54, 0x43, 0xab, 0xda, 0xae,
	0x15, 0xb7, 0x35, 0xdb, 0x72, 0xb0, 0x1c, 0xfc, 0xf2, 0xe4, 0xe2, 0xa3, 0xc4, 0xf3, 0x5c, 0x8d,
	0x68, 0x36, 0x0d, 0xd3, 0x76, 0x74, 0x4c, 0x6d, 0x4c, 0x65, 0x9b, 0x9a, 0x7e, 0xcc, 0xa6, 0x66,
	0x18, 0xd8, 0xe5, 0x01, 0x35, 0xb0, 0x64, 0x6e, 0x84, 0xa1, 0x82, 0x89, 0x4d, 0xcc, 0xfd, 0xfe,
	0x3f, 0xee, 0x2d, 0x7f, 0x13, 0xc0, 0xed, 0x3a, 0x35, 0x5f, 0xbb, 0x86, 0xc6, 0xd0, 0xab, 0x40,
	0x03, 0x3e, 0x07, 0x79, 0xcd, 0x63, 0x17, 0x98, 0x58, 0xac, 0x2b, 0x0a, 0x25, 0xa1, 0x92, 0x3f,
	0x15, 0xbf, 0x7f, 0x3d, 0x2c, 0x84, 0xc7, 0xbd, 0x30, 0x0c, 0x82, 0x28, 0x6d, 0x30, 0x62, 0x39,
	0xa6, 0x32, 0x49, 0x85, 0x67, 0x20, 0xc7, 0xbb, 0x14, 0x37, 0x4a, 0x42, 0xe5, 0xe6, 0x51, 0xa9,
	0x9a, 0x34, 0x7a, 0x95, 0x2b, 0x9d, 0xe6, 0x2f, 0x7f, 0xed, 0xa7, 0xbe, 0x0c, 0x7b, 0x07, 0x82,
	0x12, 0x96, 0x9e, 0x9c, 0x7c, 0x18, 0xf6, 0x0e, 0x26, 0x87, 0x7e, 0x1c, 0xf6, 0x0e, 0x1e, 0xcf,
	0x42, 0xe9, 0x8c, 0xb1, 0xcc, 0x35, 0x5e, 0xde, 0x05, 0x3b, 0x73, 0x2e, 0x05, 0x51, 0x17, 0x3b,
	0x14, 0x95, 0x3f, 0x6f, 0x80, 0x7b, 0x75, 0x6a, 0x36, 0xbc, 0xa6, 0x6d, 0xb1, 0x33, 0x5e, 0xef,
	0x31, 0x0b, 0x3b, 0xf0, 0x08, 0x6c, 0xea, 0x04, 0x69, 0x0c, 0x93, 0xa5, 0xb3, 0x8e, 0x12, 0xe1,
	0x0e, 0xd8, 0xf4, 0x28, 0x22, 0xaa, 0x65, 0x04, 0xa3, 0xe6, 0x95, 0x9c, 0x6f, 0x9e, 0x1b, 0xf0,
	0x21, 0xb8, 0xf5, 0x16, 0x59, 0xe6, 0x05, 0x53, 0xbd, 0xa0, 0x0b, 0x31, 0x5d, 0x12, 0x2a, 0x19,
	0x65, 0x8b, 0x3b, 0x79, 0x67, 0xf0, 0x29, 0xd8, 0xd6, 0xb1, 0xd3, 0x46, 0xc4, 0x44, 0x8e, 0x8e,
	0x54, 0xea, 0x22, 0x64, 0x88, 0x99, 0x20, 0xf1, 0xce, 0x54, 0xa0, 0xe1, 0xfb, 0x61, 0x0d, 0x14,
	0x34, 0x5d, 0xf7, 0x88, 0xa6, 0x77, 0x55, 0xcb, 0x76, 0x09, 0x6e, 0x23, 0x1b, 0x39, 0x4c, 0xcc,
	0x06, 0xf9, 0x77, 0x47, 0xb1, 0xf3, 0x49, 0x08, 0x1e, 0x02, 0xa8, 0x4f, 0x4d, 0xa8, 0x52, 0x1d,
	0x13, 0x24, 0xe6, 0x82, 0x82, 0xed, 0xe9, 0x48, 0xc3, 0x0f, 0x9c, 0x6c, 0xf9, 0xc4, 0x47, 0xa3,
	0x95, 0xf7, 0xc1, 0x5e, 0x2c, 0xa7, 0x31, 0xc9, 0x9f, 0x9c, 0xe4, 0x99, 0x9f, 0x8f, 0xfe, 0x99,
	0x64, 0x01, 0x64, 0x2d, 0xc7, 0x40, 0x9d, 0x90, 0x23, 0x37, 0xa6, 0xf9, 0xa6, 0x17, 0xf3, 0xcd,
	0xac, 0xca, 0x37, 0xbb, 0x26, 0xdf, 0xdc, 0xba, 0x7c, 0x37, 0x13, 0xf8, 0xc2, 0xfb, 0x20, 0xcf,
	0x2c, 0x1b, 0x51, 0xa6, 0xd9, 0xae, 0x78, 0xa3, 0x24, 0x54, 0xd2, 0xca, 0xc4, 0x11, 0x4b, 0x3f,
	0xca, 0x76, 0x9e, 0x3e, 0x9f, 0xf4, 0x3f, 0xfd, 0xeb, 0xa0, 0x1f, 0x65, 0x3b, 0xa6, 0x8f, 0x03,
	0xf8, 0x2f, 0x51, 0x0b, 0x5d, 0x17, 0xfc, 0xd8, 0x8e, 0xa2, 0x82, 0xa3, 0x8e, 0x8e, 0xfe, 0x64,
	0x40, 0xba, 0x4e, 0x4d, 0xd8, 0x02, 0x5b, 0x33, 0x3b, 0xfc, 0x49, 0xf2, 0xee, 0x9d, 0x5b, 0x91,
	0xc5, 0xda, 0xca, 0xa9, 0x23, 0x55, 0xf8, 0x0e, 0xc0, 0x98, 0x4d, 0x2a, 0x2f, 0x3c, 0x28, 0x5a,
	0x50, 0x3c, 0x5e, 0xb3, 0x60, 0x5a, 0x3f, 0x66, 0xff, 0x2c, 0xd6, 0x8f, 0x16, 0x2c, 0xd1, 0x4f,
	0x7e, 0x0a, 0x7d, 0xfd, 0x98, 0x27, 0x50, 0x5e, 0x01, 0xe4, 0x1a, 0xfa, 0xc9, 0xf7, 0xd0, 0xd7,
	0x8f, 0xb9, 0x84, 0x8b, 0xf5, 0xa3, 0x05, 0x4b, 0xf4, 0x93, 0x6f, 0x5d, 0x31, 0xfb, 0xde, 0x7f,
	0x67, 0x9f, 0x1e, 0x5f, 0xf6, 0x25, 0xe1, 0xaa, 0x2f, 0x09, 0xbf, 0xfb, 0x92, 0xf0, 0x69, 0x20,
	0xa5, 0xae, 0x06, 0x52, 0xea, 0xc7, 0x40, 0x4a, 0xbd, 0xd9, 0x4b, 0x7a, 0x65, 0xb3, 0xae, 0x8b,
	0x68, 0x33, 0x17, 0x7c, 0x7c, 0x3c, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xab, 0xa0, 0x8a, 0x90,
	0x3f, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// SubmitContribution defines the SubmitContribution RPC.
	SubmitContribution(ctx context.Context, in *MsgSubmitContribution, opts ...grpc.CallOption) (*MsgSubmitContributionResponse, error)
	// CreateContribution defines the CreateContribution RPC.
	CreateContribution(ctx context.Context, in *MsgCreateContribution, opts ...grpc.CallOption) (*MsgCreateContributionResponse, error)
	// UpdateContribution defines the UpdateContribution RPC.
	UpdateContribution(ctx context.Context, in *MsgUpdateContribution, opts ...grpc.CallOption) (*MsgUpdateContributionResponse, error)
	// DeleteContribution defines the DeleteContribution RPC.
	DeleteContribution(ctx context.Context, in *MsgDeleteContribution, opts ...grpc.CallOption) (*MsgDeleteContributionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/contribledger.contrib.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitContribution(ctx context.Context, in *MsgSubmitContribution, opts ...grpc.CallOption) (*MsgSubmitContributionResponse, error) {
	out := new(MsgSubmitContributionResponse)
	err := c.cc.Invoke(ctx, "/contribledger.contrib.v1.Msg/SubmitContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateContribution(ctx context.Context, in *MsgCreateContribution, opts ...grpc.CallOption) (*MsgCreateContributionResponse, error) {
	out := new(MsgCreateContributionResponse)
	err := c.cc.Invoke(ctx, "/contribledger.contrib.v1.Msg/CreateContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateContribution(ctx context.Context, in *MsgUpdateContribution, opts ...grpc.CallOption) (*MsgUpdateContributionResponse, error) {
	out := new(MsgUpdateContributionResponse)
	err := c.cc.Invoke(ctx, "/contribledger.contrib.v1.Msg/UpdateContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteContribution(ctx context.Context, in *MsgDeleteContribution, opts ...grpc.CallOption) (*MsgDeleteContributionResponse, error) {
	out := new(MsgDeleteContributionResponse)
	err := c.cc.Invoke(ctx, "/contribledger.contrib.v1.Msg/DeleteContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// SubmitContribution defines the SubmitContribution RPC.
	SubmitContribution(context.Context, *MsgSubmitContribution) (*MsgSubmitContributionResponse, error)
	// CreateContribution defines the CreateContribution RPC.
	CreateContribution(context.Context, *MsgCreateContribution) (*MsgCreateContributionResponse, error)
	// UpdateContribution defines the UpdateContribution RPC.
	UpdateContribution(context.Context, *MsgUpdateContribution) (*MsgUpdateContributionResponse, error)
	// DeleteContribution defines the DeleteContribution RPC.
	DeleteContribution(context.Context, *MsgDeleteContribution) (*MsgDeleteContributionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) SubmitContribution(ctx context.Context, req *MsgSubmitContribution) (*MsgSubmitContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitContribution not implemented")
}
func (*UnimplementedMsgServer) CreateContribution(ctx context.Context, req *MsgCreateContribution) (*MsgCreateContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContribution not implemented")
}
func (*UnimplementedMsgServer) UpdateContribution(ctx context.Context, req *MsgUpdateContribution) (*MsgUpdateContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContribution not implemented")
}
func (*UnimplementedMsgServer) DeleteContribution(ctx context.Context, req *MsgDeleteContribution) (*MsgDeleteContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContribution not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contribledger.contrib.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitContribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contribledger.contrib.v1.Msg/SubmitContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitContribution(ctx, req.(*MsgSubmitContribution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateContribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contribledger.contrib.v1.Msg/CreateContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateContribution(ctx, req.(*MsgCreateContribution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateContribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contribledger.contrib.v1.Msg/UpdateContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateContribution(ctx, req.(*MsgUpdateContribution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteContribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contribledger.contrib.v1.Msg/DeleteContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteContribution(ctx, req.(*MsgDeleteContribution))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contribledger.contrib.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SubmitContribution",
			Handler:    _Msg_SubmitContribution_Handler,
		},
		{
			MethodName: "CreateContribution",
			Handler:    _Msg_CreateContribution_Handler,
		},
		{
			MethodName: "UpdateContribution",
			Handler:    _Msg_UpdateContribution_Handler,
		},
		{
			MethodName: "DeleteContribution",
			Handler:    _Msg_DeleteContribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contribledger/contrib/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitContribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitContribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitContribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ContributionScore != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ContributionScore))
		i--
		dAtA[i] = 0x30
	}
	if m.AccuracyImprovement != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AccuracyImprovement))
		i--
		dAtA[i] = 0x28
	}
	if m.ConvergenceSpeed != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ConvergenceSpeed))
		i--
		dAtA[i] = 0x20
	}
	if m.WeightUpdate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WeightUpdate))
		i--
		dAtA[i] = 0x18
	}
	if len(m.UserId) > 0 {
		i -= len(m.UserId)
		copy(dAtA[i:], m.UserId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UserId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitContributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitContributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitContributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateContribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateContribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateContribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x40
	}
	if m.ContributionScore != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ContributionScore))
		i--
		dAtA[i] = 0x38
	}
	if m.AccuracyImprovement != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AccuracyImprovement))
		i--
		dAtA[i] = 0x30
	}
	if m.ConvergenceSpeed != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ConvergenceSpeed))
		i--
		dAtA[i] = 0x28
	}
	if m.WeightUpdate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WeightUpdate))
		i--
		dAtA[i] = 0x20
	}
	if len(m.UserId) > 0 {
		i -= len(m.UserId)
		copy(dAtA[i:], m.UserId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UserId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateContributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateContributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateContributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateContribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateContribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateContribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x40
	}
	if m.ContributionScore != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ContributionScore))
		i--
		dAtA[i] = 0x38
	}
	if m.AccuracyImprovement != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AccuracyImprovement))
		i--
		dAtA[i] = 0x30
	}
	if m.ConvergenceSpeed != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ConvergenceSpeed))
		i--
		dAtA[i] = 0x28
	}
	if m.WeightUpdate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WeightUpdate))
		i--
		dAtA[i] = 0x20
	}
	if len(m.UserId) > 0 {
		i -= len(m.UserId)
		copy(dAtA[i:], m.UserId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UserId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateContributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateContributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateContributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteContribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteContribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteContribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteContributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteContributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteContributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitContribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WeightUpdate != 0 {
		n += 1 + sovTx(uint64(m.WeightUpdate))
	}
	if m.ConvergenceSpeed != 0 {
		n += 1 + sovTx(uint64(m.ConvergenceSpeed))
	}
	if m.AccuracyImprovement != 0 {
		n += 1 + sovTx(uint64(m.AccuracyImprovement))
	}
	if m.ContributionScore != 0 {
		n += 1 + sovTx(uint64(m.ContributionScore))
	}
	return n
}

func (m *MsgSubmitContributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateContribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WeightUpdate != 0 {
		n += 1 + sovTx(uint64(m.WeightUpdate))
	}
	if m.ConvergenceSpeed != 0 {
		n += 1 + sovTx(uint64(m.ConvergenceSpeed))
	}
	if m.AccuracyImprovement != 0 {
		n += 1 + sovTx(uint64(m.AccuracyImprovement))
	}
	if m.ContributionScore != 0 {
		n += 1 + sovTx(uint64(m.ContributionScore))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	return n
}

func (m *MsgCreateContributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateContribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WeightUpdate != 0 {
		n += 1 + sovTx(uint64(m.WeightUpdate))
	}
	if m.ConvergenceSpeed != 0 {
		n += 1 + sovTx(uint64(m.ConvergenceSpeed))
	}
	if m.AccuracyImprovement != 0 {
		n += 1 + sovTx(uint64(m.AccuracyImprovement))
	}
	if m.ContributionScore != 0 {
		n += 1 + sovTx(uint64(m.ContributionScore))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	return n
}

func (m *MsgUpdateContributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteContribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteContributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitContribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitContribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitContribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightUpdate", wireType)
			}
			m.WeightUpdate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WeightUpdate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConvergenceSpeed", wireType)
			}
			m.ConvergenceSpeed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConvergenceSpeed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccuracyImprovement", wireType)
			}
			m.AccuracyImprovement = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccuracyImprovement |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionScore", wireType)
			}
			m.ContributionScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContributionScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitContributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitContributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitContributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateContribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateContribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateContribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightUpdate", wireType)
			}
			m.WeightUpdate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WeightUpdate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConvergenceSpeed", wireType)
			}
			m.ConvergenceSpeed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConvergenceSpeed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccuracyImprovement", wireType)
			}
			m.AccuracyImprovement = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccuracyImprovement |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionScore", wireType)
			}
			m.ContributionScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContributionScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateContributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateContributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateContributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateContribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateContribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateContribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightUpdate", wireType)
			}
			m.WeightUpdate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WeightUpdate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConvergenceSpeed", wireType)
			}
			m.ConvergenceSpeed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConvergenceSpeed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccuracyImprovement", wireType)
			}
			m.AccuracyImprovement = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccuracyImprovement |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionScore", wireType)
			}
			m.ContributionScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContributionScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateContributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateContributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateContributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteContribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteContribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteContribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteContributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteContributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteContributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
